---
swagger: "2.0"
info:
  description: A Deployment Management Application for Kubernetes
  title: konveyer
  version: 1.0.0
basePath: /v1
paths:
  /project:
    get:
      tags:
        - projects
      operationId: find_projects
      parameters:
        - name: limit
          in: query
          type: integer
          format: int32
          default: 10
      responses:
        200:
          description: list of projects
          schema:
            type: array
            items:
              $ref: "#/definitions/project"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - projects
      summary: adds a project to be managed
      operationId: add_project
      description: Adds an item to the system
      parameters:
      - in: body
        name: projectName
        description: Application item to add
        schema:
          $ref: '#/definitions/project'
      responses:
        201:
          description: OK Created
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
  /project/{projectName}:
    get:
      tags:
        - projects
      operationId: describe_projects
      parameters:
        - in: path
          name: projectName
          description: Name of Project your requesting information on
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/project"
        400:
          description: bad input parameter
          schema:
            $ref: "#/definitions/error"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  project:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 3
        example: project1
  arrayOfProjects:
    type: array
    items: 
      $ref: "#/definitions/project"
    example:
      - name: project1
      - name: project2
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
# Descriptions of common responses
responses:
  200:
    description: OK
  201:
    description: OK Created
  400:
    description: Bad request. Verify Data Format
  401:
    description: Unauthorized
  404:
    description: The specified resource was not found
  NotFound:
    description: The specified resource was not found
  Unauthorized:
    description: Unauthorized

produces:
- application/json
consumes:
- application/json
schemes:
- http
